
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_BUTTON_DEVICE_ID,
		XPAR_BUTTON_BASEADDR,
		XPAR_BUTTON_INTERRUPT_PRESENT,
		XPAR_BUTTON_IS_DUAL
	},
	{
		XPAR_DIP_DEVICE_ID,
		XPAR_DIP_BASEADDR,
		XPAR_DIP_INTERRUPT_PRESENT,
		XPAR_DIP_IS_DUAL
	}
};


